BGE settings for Reblocking and JointCalling pipelines
broadinstitute/warp pull request #1076
Opened 2023-09-08 20:38 UTC by meganshand

### Description

This is a draft of how we'd like to run joint calling on BGE with a few changes to the current pipeline:

- Use an updated variant calling interval list (bge v1.1 calling intervals)
- Reblocking
  * Use an updated version of ReblockGVCFs to work with DRAGEN input
  * Added argument to strip “PRI” annotation: `--format-annotations-to-remove PRI`
  * Add argument to move site level filters to genotype level instead: `--add-site-filters-to-genotype` 
  * No need to do extra blocking at this step since the block sizes are now set in the DRAGEN/single sample pipeline
- Filtering
  * Allow for the option to use the newer VETS pipeline rather than VQSR in JointGenotyping
  * Hard filter sites that land outside of the targeted regions (but within the exome variant calling interval list)
  * Train the VETS model only over the targeted regions of the BGE (where there's expected coverage)
  * Provide the SCORE annotation calculated by the VETS model for all variants, but don't use it as an applied filter so that users can choose their own cutoff values

Making two paths in the JointCalling pipeline for two different filtering strategies was a bit messy, so I'm happy to hear if there are any recommendations on how to clean that up. I also tried to run the tests that already exist for these workflows, but ran into errors that seemed unrelated. 

@jessicaway For now I left out any changes to the ByChromosome workflows and we can cross that bridge when we come to it.

----

### Checklist 

If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) and notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [x] Did you add inputs, outputs, or tasks to a workflow?
- [x] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [x] If you made a changelog update, did you update the pipeline version number?

2023-09-18 18:25 UTC, meganshand commented
@jessicaway @samuelklee This is ready for review. As discussed in the meeting this morning the two remaining issues are:

- We'll need to update the version of GATK once it's been released
- Test files still need to be copied into the appropriate bucket for all the tests to pass here

I don't think either of these should stop an initial review though. Thanks!

2023-09-18 18:26 UTC, meganshand commented
@ekiernan This PR will need some documentation updates for the BGE pipeline. I also submitted a request through the portal. Happy to work with you on this.

2023-09-18 18:39 UTC, samuelklee commented
Great, thanks @meganshand! Should be able to get an initial review back to you in the next couple days.

Would be great to also get https://github.com/broadinstitute/gatk/pull/8131 in before the next GATK release. Let's chat about whether that necessitates any changes here---I don't think it should, but that PR has been on the back burner for a bit, so I'll have to double check.

2023-09-20 16:15 UTC, samuelklee requested changes
Thanks @meganshand, just a few minor comments/questions from me!

2023-09-20 16:15 UTC, samuelklee commented on pipelines/broad/dna_seq/germline/joint_genotyping/JointGenotyping.wdl
> +    String resource_args = " --resource:hapmap,training=true,calibration=true " + hapmap_resource_vcf +
Would be nice to expose this and demote the default resources from required arguments at some point, but this is fine for now.

2023-09-20 16:15 UTC, samuelklee commented on pipelines/broad/dna_seq/germline/joint_genotyping/JointGenotyping.wdl
> +  if (run_vets) {
Ideally, we'd have separate VQSR and VETS subworkflows, and the latter would be a direct import of the JointVcfFiltering WDL in the GATK repo. Either we'll get there in the future or we'll remove VQSR, let's see which happens first!

2023-09-20 16:15 UTC, samuelklee commented on pipelines/broad/dna_seq/germline/joint_genotyping/reblocking/ReblockGVCF.changelog.md
> +# 2.1.6
Do you need to update some of these changelogs now that #1081 is in?

2023-09-20 16:15 UTC, samuelklee commented on pipelines/broad/dna_seq/germline/joint_genotyping/test_inputs/Scientific/bge.json
> +  "JointGenotyping.snp_recalibration_annotation_values": ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"],
Why are these not allele-specific annotations, when `use_allele_specific_annotations = true` below?

2023-09-20 16:15 UTC, samuelklee commented on pipelines/broad/dna_seq/germline/joint_genotyping/test_inputs/Scientific/bge.json
> +  "JointGenotyping.unpadded_intervals_file": "",
Were `unpadded_intervals_file`, `eval_interval_list`, and `targets_interval_list` intentionally left empty for now?

2023-09-20 16:15 UTC, samuelklee commented on tasks/broad/JointGenotypingTasks.wdl
> +    File? targets_interval_list # filters out all variants outside of the targets interval list for targetted sequencing
`targetted` -> `targeted`.

I'm also unclear about whether such changes to tasks need to be reflected in a changelog somewhere?

2023-12-15 21:11 UTC, meganshand commented
The failing smart tests here are due to a change in the VCF header when updating to GATK 4.5.0.0:

```
< ##INFO=<ID=RAW_GT_COUNT,Number=3,Type=Integer,Description="Counts of genotypes w.r.t. the reference allele in the following order: 0/0, 0/*, */*, i.e. all alts lumped together; for use in calculating excess heterozygosity">
---
> ##INFO=<ID=RAW_GT_COUNT,Number=3,Type=Integer,Description="Counts of genotypes w.r.t. the reference allele: 0/0, 0/*, */*, i.e. all alts lumped together; for use in calculating excess heterozygosity">
```

This change seems harmless to me, but I'm not sure who needs to sign off on this change. The PR with the rest of the GATK updates to 4.5.0.0 is still in progress, but should be coming soon.

2024-02-02 15:19 UTC, meganshand commented
Failing Scientific Tests that can be updated:

- JointGenotyping: BGE test is failing because the truth data is out of data. This can safely be updated as these differences are expected.
- ReblockGVCFs: Tests are failing because documentation on a header line changed (see comment above). This can safely be updated.
- VariantCalling: Same header line change as ReblockGVCFs. This can be updated.

2024-02-02 15:53 UTC, jessicaway approved these changes

2024-02-05 19:31 UTC, nikellepetrillo approved these changes

2024-02-06 16:41 UTC, nikellepetrillo commented
after merging in the latest develop, we re-ran JG, variant calling, and reblocking against Megan's truth (which was previously validated):

https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/65222/console
https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/65156/console/
https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/65155/console

2024-02-06 16:43 UTC, merged