Staging -> Master
broadinstitute/warp pull request #118
Opened 2020-10-22 19:13 UTC by gbggrant

Staging -> Master

2020-10-22 19:33 UTC, jessicaway approved these changes

2020-10-22 19:35 UTC, sophiacrennan approved these changes

2020-10-23 12:49 UTC, ekiernan requested changes
@gbggrant In the process of making the vuepress site, I removed the Optimus and scATAC READMEs. They are now back on the develop branch. Could we merge develop back into staging before merging to master?

2020-10-23 20:42 UTC, ekiernan approved these changes

2020-10-24 11:03 UTC, gbggrant commented
Running smart test again at: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-smart-tests/323/
(https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-smart-tests/315 ran plumbing dev branch??)

2020-10-27 14:00 UTC, gbggrant commented
Results of running scientific tests (https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-smart-tests/323/)
staging -> master PR.

3 failures (all in validation):
1. Arrays - expected failure (BafRegressMetrics is a class in picard-private - not visible to picard tool 'CompareMetrics' - need to do a code fix for this)
2. Exome Germline Single Sample.  Two verification workflows failed.
	1. CHMI_CHMI3_Nex1 - minor diffs in TOTAL_HET_DEPTH and SNP_REFERENCE_BIAS.  Failure consistent with non-determinism.
	2. NA17-308.  g.vcf differs from truth by 79 lines.   Failure consistent with non-determinism.
3. Exome Reprocessing.  Two verification workflows failed.
	1. D5327.NA12878.  minor diffs in TOTAL_HET_DEPTH.  Failure consistent with non-determinism
	2. NA17-308.  g.vcf differs from truth by 106 lines.  Failure consistent with non-determinism.

2020-10-27 14:00 UTC, merged