Fixed minor issues in minor issues in BuildIndices
broadinstitute/warp pull request #154
Opened 2020-11-26 00:46 UTC by TimoLassmann

1) the output file names for two tasks was identical causing errors when running cromwell with the "final_workflow_outputs_dir" option.

2) the task "BuildHisat2SnpHaplotypeSplicing" pointed to scripts not found in the container. This is now fixed and _seems_ to work.

3) Minor: the example "mouse_inputs.json" input file points to version 150 of dbsnp but the latest version on UCSC (https://hgdownload.cse.ucsc.edu/goldenPath/mm10/database/) seems to be 142.

2021-01-08 18:46 UTC, khajoue2 approved these changes

2021-01-12 15:08 UTC, kishorikonwar approved these changes

2021-01-12 15:38 UTC, gbggrant requested changes

2021-01-12 15:38 UTC, gbggrant commented on pipelines/skylab/build_indices/BuildIndices.wdl
> +        memory: "50 GiB"
That's a lot of memory - are you sure that's all needed for wget and gunzip?
Also - the spacing is off.  memory should align with disks.

2021-01-12 15:38 UTC, gbggrant commented on pipelines/skylab/build_indices/BuildIndices.wdl
> +    if ! which hisat2_extract_snps_haplotypes_UCSC.py ; then
Can you indent these if blocks appropriately?

2021-02-22 16:29 UTC, kbergin commented
Hi @TimoLassmann would you be able to rebase and complete this PR? We would appreciate it!

2021-03-24 12:16 UTC, nikellepetrillo commented
Hi @TimoLassmann, a fix for the output file name in the BuildRsem task has been merged in here: https://github.com/broadinstitute/warp/pull/267

When you can, can you please rebase your pr and follow up on the changes requested? Thanks!

2022-01-12 19:02 UTC, gbggrant commented
Hi @TimoLassmann - we are closing this for now. If you are interested in proceeding with this PR, can you reopen and update?

2022-01-12 19:02 UTC, closed without merging