wd_gl-1824 Imputation-callset_name
broadinstitute/warp pull request #494
Opened 2021-11-04 11:29 UTC by wjdingman1

Makes the input to the imputation pipeline 'output_callset_name' available as output under the name 'output_callset_name_output'

2021-11-04 14:11 UTC, ekiernan requested changes

2021-11-04 14:11 UTC, ekiernan commented on pipelines/broad/arrays/imputation/Imputation.wdl
> +    String output_callset_name_output = output_callset_name
```suggestion
String callset_name_output = output_callset_name
```

2021-11-04 14:17 UTC, ekiernan commented on pipelines/broad/arrays/imputation/Imputation.wdl
> +    String output_callset_name_output = output_callset_name
Whatever name we decide on, I just want to make sure it gets added to the outputs section in the documentation.

2021-11-04 15:10 UTC, ekiernan approved these changes

2021-11-04 18:37 UTC, cheyenne-gold approved these changes

2021-11-09 16:32 UTC, wjdingman1 commented
Closing this, Hornet team no longer needs this feature

2021-11-09 16:32 UTC, closed without merging