Adding contamination estimation to the RNA pipeline
broadinstitute/warp pull request #629
Opened 2022-02-24 23:57 UTC by takutosato

I still need to update the part of the wdl that sends output to TDR.

An analysis of RNA contamination here: https://github.com/broadinstitute/hydro.gen/issues/890

2022-02-25 16:50 UTC, kayleemathews commented on pipelines/broad/rna_seq/RNAWithUMIsPipeline.wdl
> +    population_vcf: "VCF file for contaimation estimation containing common SNP sites from population wide studies like ExAC or gnomad"
```suggestion
    population_vcf: "VCF file for contamination estimation containing common SNP sites from population-wide studies like ExAC or gnomAD"
```

2022-02-25 16:50 UTC, kayleemathews commented on pipelines/broad/rna_seq/RNAWithUMIsPipeline.wdl
> +    population_vcf_index: "Index for the population vcf"
```suggestion
    population_vcf_index: "Index file for the population vcf"
```

2022-03-03 22:07 UTC, kayleemathews commented on pipelines/broad/internal/rna_seq/BroadInternalRNAWithUMIs.wdl
>      tdr_staging_bucket: "Optional String defining the GCS bucket to use to stage files for loading to TDR. Workspace bucket is recommended"
```suggestion
    tdr_dataset_uuid: "Optional string used to define the Terra Data Repo (TDR) dataset to which outputs will be ingested"
    tdr_sample_id: "Optional string used to identify the sample being processed; this is the primary key in the TDR dataset"
    tdr_staging_bucket: "Optional string defining the GCS bucket to use to stage files for loading to TDR; the workspace bucket is recommended"
```

2022-03-29 15:34 UTC, takutosato commented
@mmorgantaylor It says merging is blocked---maybe because it needs reviewers? I requested a review from you and @gbggrant. Or, if the merge button is not grayed out for you please free to just merge it too.

2022-03-29 15:51 UTC, mmorgantaylor approved these changes
the TDR parts look good to me - would be great to get George's thumb too for the contamination bit

2022-03-29 16:06 UTC, gbggrant requested changes
Looks good. I need to add the contamination VCFs to the test files for the 'RNAWithUMIsPIpeline' - will do that shortly (so that the tests will pass)

2022-03-29 17:31 UTC, gbggrant commented
add to whitelist

2022-03-29 17:50 UTC, merged

2022-03-30 18:53 UTC, takutosato commented
Thank you @gbggrant and @mmorgantaylor