KM document slideseq test data
broadinstitute/warp pull request #899
Opened 2023-01-09 17:49 UTC by kayleemathews

2023-01-09 21:32 UTC, ekiernan requested changes
I suggest adding a few minor changes to the cropping description just to clarify for folks.

2023-01-19 16:57 UTC, khajoue2 approved these changes
LGTM

2023-01-27 21:12 UTC, ekiernan commented on pipelines/skylab/slideseq/test_inputs/test_data_overview.md
> +The plumbing input listed above was downsampled using a [custom python script](Plumbing/slideseq_downsample.py) to first crop the sample from 2500 to 4000 in the x-dimension and 1000 to 4200 in the y
```suggestion
The plumbing input FASTQ listed above was downsampled using a [custom python script](Plumbing/slideseq_downsample.py). First, a PDF image of the sample puck was examined and the XY coordinates for a region of interest were selected. A bead position TSV containing the XY coordinates for the puck's barcodes was used as input to the custom script and the TSV was cropped 2500 to 4000 in the x-dimension and 1000 to 4200 in the y-dimension. Next, 10 random cells were sampled for each 30 by 30 region in the cropped TSV. The list of sampled cells was then used to create new, downsampled FASTQ files using a second [custom script](https://github.com/broadinstitute/warp-tools/blob/master/fastqpreprocessing/src/samplefastq.cpp) from the [warp-tools GitHub repository](https://github.com/broadinstitute/warp-tools/tree/master). 
```

2023-02-02 12:36 UTC, kayleemathews commented on pipelines/skylab/slideseq/test_inputs/test_data_overview.md
> +* Puck_210817_11.human
Do these live anywhere other than in the SlideSeq dev workspace bucket? Somewhere public we can link to? @khajoue2

2023-02-02 12:37 UTC, kayleemathews commented on pipelines/skylab/slideseq/test_inputs/test_data_overview.md
> +The plumbing input listed above was downsampled using a [custom python script](Plumbing/slideseq_downsample.py) to first crop the sample from 2500 to 4000 in the x-dimension and 1000 to 4200 in the y
Updated

2023-02-02 15:24 UTC, merged